version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile  
    environment:
      APP_ENV: prod
      APP_SECRET: 885f80be8a00e2432a906abf4179ce1
      DATABASE_URL: "pgsql://user:password@db:5432/name_shower?serverVersion=15&charset=utf8"

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: name_shower
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
