version: '3.8'

services:
  backend:
    environment:
      APP_ENV: prod
      APP_SECRET: 885f80be8a00e2432a906abf4179ce1
      DATABASE_URL: "pgsql://user:password@db:5432/name_shower?serverVersion=15&charset=utf8"

  frontend:
    environment:
      NODE_ENV: production
