services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/php/Dockerfile
    container_name: symfony_app
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    working_dir: /var/www/html
    command: ./entrypoint.sh

  frontend:
    build:
      context: ./frontend/frontend
      dockerfile: Dockerfile
    container_name: angular_app
    volumes:
      - ./frontend/frontend:/app
    ports:
      - "4200:4200"
    command: npm run start -- --host 0.0.0.0

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
